import { 
  User, 
  Users,
  MessageSquare, 
  Clock, 
  Activity, 
  History, 
  Video, 
  DollarSign, 
  Calendar, 
  CheckCircle 
} from 'lucide-react';
import { TriageStep } from '../types/triage';

export const TRIAGE_STEPS: TriageStep[] = [
  {
    id: 1,
    title: 'Identificação',
    description: 'Como podemos te chamar e entrar em contato?',
    icon: User,
    field: 'nome',
    type: 'text',
  },
  {
    id: 2,
    title: 'Faixa Etária',
    description: 'Qual a sua faixa etária?',
    icon: Users,
    field: 'faixa_etaria',
    type: 'select',
    options: ['Infantil (até 12 anos)', 'Adolescente (13 a 17 anos)', 'Adulto (18 a 59 anos)', 'Idoso (60+ anos)'],
  },
  {
    id: 3,
    title: 'Motivo da Busca',
    description: 'Qual o principal motivo da sua busca por terapia hoje?',
    icon: MessageSquare,
    field: 'motivo',
    type: 'select',
    options: ['Ansiedade', 'Depressão', 'Relacionamentos', 'Carreira', 'Outros'],
  },
  {
    id: 4,
    title: 'Tempo de Convívio',
    description: 'Há quanto tempo você convive com essas questões?',
    icon: Clock,
    field: 'tempo_convivio',
    type: 'select',
    options: ['Poucos dias', 'Algumas semanas', 'Meses', 'Anos', 'Desde sempre'],
  },
  {
    id: 5,
    title: 'Impacto na Rotina',
    description: 'De 1 a 10, quanto isso impacta sua vida hoje?',
    icon: Activity,
    field: 'impacto_rotina',
    type: 'scale',
  },
  {
    id: 6,
    title: 'Histórico',
    description: 'Você já teve experiências anteriores com terapia?',
    icon: History,
    field: 'historico',
    type: 'select',
    options: ['Sim', 'Não'],
  },
  {
    id: 7,
    title: 'Modalidade',
    description: 'Como você prefere que aconteçam nossos encontros?',
    icon: Video,
    field: 'modalidade',
    type: 'select',
    options: ['Online', 'Presencial', 'Tanto faz'],
  },
  {
    id: 8,
    title: 'Período de Preferência',
    description: 'Qual o melhor período para suas sessões?',
    icon: Calendar,
    field: 'periodo',
    type: 'select',
    options: ['Manhã', 'Tarde', 'Noite'],
  },
  {
    id: 9,
    title: 'Prontidão para a Mudança',
    description: 'O processo terapêutico exige dedicação. Caso tenhamos uma vaga disponível, você estaria pronto para iniciar sua jornada ainda esta semana?',
    icon: CheckCircle,
    field: 'comprometimento',
    type: 'select',
    options: ['Sim, estou comprometido', 'Preciso de um pouco mais de tempo'],
  },
];
